version: "3"

services:
  rust:
    build: ./docker/rust
    volumes:
      - ./wasm_binaries:/home/wasm_presentation/wasm_binaries
      - ./html:/home/wasm_presentation/html
    command: bash -xe "create_wasm_binaries.sh"

  php:
    build: ./docker/php
    volumes:
      - ./wasm_binaries:/home/wasm_presentation/wasm_binaries
      - ./docker/php/scripts:/home/wasm_presentation/scripts
    depends_on:
      - rust
    tty: true

  python:
    build: ./docker/python
    ports: 
      - 8000:8000
    volumes:
    - ./wasm_binaries:/home/wasm_presentation/wasm_binaries
    - ./docker/python/scripts:/home/wasm_presentation/scripts
    - ./html:/home/wasm_presentation/html
    command: bash -c "python3 -m http.server -d /home/wasm_presentation/html"
    depends_on:
      - rust
    tty: true


